/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#ffb3b0",
        "on-primary": "#680010",
        "primary-container": "#a81326",
        "on-primary-container": "#ffb7b4",
        "primary-fixed": "#ffdad8",
        "primary-fixed-dim": "#ffb3b0",
        "on-primary-fixed": "#410007",
        "on-primary-fixed-variant": "#92001b",
        "inverse-primary": "#b6202f",
        "secondary": "#ffb95f",
        "on-secondary": "#472a00",
        "secondary-container": "#ee9800",
        "on-secondary-container": "#5b3800",
        "secondary-fixed": "#ffddb8",
        "secondary-fixed-dim": "#ffb95f",
        "on-secondary-fixed": "#2a1700",
        "on-secondary-fixed-variant": "#653e00",
        "tertiary": "#ffb3b1",
        "on-tertiary": "#680011",
        "tertiary-container": "#a1222c",
        "on-tertiary-container": "#ffb7b4",
        "tertiary-fixed": "#ffdad8",
        "tertiary-fixed-dim": "#ffb3b1",
        "on-tertiary-fixed": "#410007",
        "on-tertiary-fixed-variant": "#8e1221",
        "surface": "#131315",
        "surface-dim": "#131315",
        "surface-bright": "#39393b",
        "surface-variant": "#353437",
        "on-surface-variant": "#e2bebc",
        "surface-container-lowest": "#0e0e10",
        "surface-container-low": "#1b1b1d",
        "surface-container": "#201f21",
        "surface-container-high": "#2a2a2c",
        "surface-container-highest": "#353437",
        "surface-tint": "#ffb3b0",
        "background": "#131315",
        "on-background": "#e5e1e4",
        "on-surface": "#e5e1e4",
        "inverse-surface": "#e5e1e4",
        "inverse-on-surface": "#303032",
        "outline": "#a98987",
        "outline-variant": "#5a403f",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "unit-2xs": "0.25rem",
        "unit-xs": "0.5rem",
        "unit-sm": "0.75rem",
        "unit-md": "1rem",
        "unit-lg": "1.5rem",
        "unit-xl": "2rem",
        "unit-2xl": "3rem",
        "unit-3xl": "4rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "1.5rem",
        "container-max": "1280px",
      },
      fontFamily: {
        "display": ["Oswald", "sans-serif"],
        "headline-lg": ["Oswald", "sans-serif"],
        "headline-lg-mobile": ["Oswald", "sans-serif"],
        "headline-md": ["Oswald", "sans-serif"],
        "headline-sm": ["Oswald", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Oswald", "sans-serif"],
        "label-md": ["Oswald", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "label-lg": ["16px", { lineHeight: "20px", letterSpacing: "0.06em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "28px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "24px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "44px", letterSpacing: "0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "32px", letterSpacing: "0.02em", fontWeight: "700" }],
        "display": ["56px", { lineHeight: "60px", letterSpacing: "0.04em", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
